### ISSUE TITLE
Doesn't switch in demo unless changed pages

### ISSUE THREAD

**Issue by peteruithoven** [TeamWertarbyte/material-ui-password-field#13]
For some reason, it doesn't seem to switch between hidden and shown in the demo. After going to another page and going back it does work. 
![peek 2017-08-03 10-24](https://user-images.githubusercontent.com/523210/28912881-508c9a28-7836-11e7-8b94-4e4066bd5389.gif)

**Comment by leMaik** [comment]
This is because the touchtap-plugin is registered too late, I'll fix that.

The storybook demo is somewhat deprecated anyway (but still useful during development). See our [styleguide](https://mui.wertarbyte.com/#material-ui-password-field) for a better demo that actually works.

**Comment by peteruithoven** [comment]
Thanks for the clarification, I copied the old url from this repo a long time ago.

**Comment by leMaik** [comment]
@peteruithoven Fixed anyway. :wink:

**Comment by peteruithoven** [comment]
Thanks! ;)

Great collection of components on that styleguide btw.

**Comment by leMaik** [comment]
@peteruithoven It's not even complete, unfortunately. A chip input, a fullscreen dialog and maybe one or two more components are missing.
