### ISSUE TITLE
Support for material v1

### ISSUE THREAD

**Issue by stefensuhat** [TeamWertarbyte/material-ui-password-field#15]

**Comment by leMaik** [comment]
This is the very next component we'll port. :+1: 
We'll just wait for material-ui's next beta release which will include _input adornments_.

**Comment by leMaik** [comment]
Yay, [material-ui@1.0.0-beta.18](https://github.com/callemall/material-ui/releases/tag/v1.0.0-beta.18) was published. :tada: Time to port this component…

**Comment by leMaik** [comment]
@stefensuhat Please checkout the first release of the port: `npm i --save material-ui-password-field@next` and tell me what you think about it! :tada:

**Comment by stefensuhat** [comment]
it works properly. 👯‍♂️

**Comment by stefensuhat** [comment]
Update:

Hint text doesn't work. Error text either.

**Comment by leMaik** [comment]
@stefensuhat This component is an `Input`, it doesn't directly support error and hint texts. I just didn't update the examples yet. Check out the Material-UI `TextField` examples to see how to combine this component with elements for error text and hint texts.
