### ISSUE TITLE
Demo should be updated to show how to add a label (v1.x)

### ISSUE THREAD

**Issue by tonymckendry** [TeamWertarbyte/material-ui-password-field#17]
None of the labels are showing up on the demo page (https://next.mui.wertarbyte.com/#material-ui-password-field) and I can't get them to work with my own attempts either. The demo code has the label prop as "floatingLabelText" which is invalid in MUI 1.x as the new prop is just "label" - neither of these work on the component as is.

**Comment by leMaik** [comment]
There is no `label` in the `Input` component, and the password component behaves just like Material-UI's `Input` component. You can add a label by using a `FormControl` as shown [here](https://material-ui-next.com/demos/text-fields/#components).

**Comment by tonymckendry** [comment]
My confusion stemmed from the fact that the docs state "In addition to the props documented above, the password field supports all props that Material-UI's TextField supports" - the TextField component does support a "label" prop.

**Comment by leMaik** [comment]
@tonymckendry It should be "also supports all props that Material-UI's `Input` component supports" now, I didn't update it when this was ported for v1.0. Would you like to submit a PR that fixes this? :+1:

**Comment by tonymckendry** [comment]
PR Submitted! Happy to help.
