### ISSUE TITLE
2.0.0-0 does not work with material-ui/core 1.0.0-rc.1

### ISSUE THREAD

**Issue by randsys** [TeamWertarbyte/material-ui-password-field#20]
Tried to use with:
    "@material-ui/core": "^1.0.0-rc.1",
    "@material-ui/icons": "^1.0.0-rc.0",
    "material-ui-password-field": "^2.0.0-0",
    "material-ui-toggle-icon": "^1.0.0-1",
but got errors since it looks like the project still references the previous material-ui version.

**Comment by leMaik** [comment]
We are working on porting all our components to Material-UI 1.0.0, but this is not done yet. A PR would be highly appreciated. :sunglasses:
