### ISSUE TITLE
Breaks server rendering

### ISSUE THREAD

**Issue by zwhitchcox** [TeamWertarbyte/material-ui-password-field#22]
So, I'm not really sure why, but when I try to server render this, the `toggle-icon` button breaks. It gives the error `document is not defined`.

**Comment by zwhitchcox** [comment]
It's actually a problem with material-ui-toggle-icon ...I sent a pr https://github.com/TeamWertarbyte/material-ui-toggle-icon/pull/4

**Comment by leMaik** [comment]
Thanks for the fix, I'll update the toggle icon and the password field asap.

**Comment by leMaik** [comment]
Done; I also updated the legacy version.

**Comment by zwhitchcox** [comment]
Niice wow, that was fast

**Comment by leMaik** [comment]
@zwhitchcox Github integration for slack FTW!
