### ISSUE TITLE
Input instead of textfield

### ISSUE THREAD

**Issue by rogueturnip** [TeamWertarbyte/material-ui-password-field#23]
Thanks for putting this together, saved me some work but I noticed that your docs are not up to date.

Seems you are using Input instead of TextField now when readme says otherwise.  Also, with Input you can no longer have helpertext or labels.

If I'm missing something please let me know.

**Comment by leMaik** [comment]
Sorry, I didn't get a notification for this issue. :disappointed: 

While the docs are out of date, here are some updated usage examples: https://github.com/TeamWertarbyte/material-ui-password-field/blob/master/src/PasswordField.md
