### ISSUE TITLE
className prop is not working

### ISSUE THREAD

**Issue by plxity** [TeamWertarbyte/material-ui-password-field#24]
When className prop is passed, It is not working.

**Comment by leMaik** [comment]
Works fine for me and adds the class to the root element. Wich version are you using?

**Comment by plxity** [comment]
I am using 1.5.0

**Comment by leMaik** [comment]
@plxity Could you provide some code that doesn't work? I need more information in order to track the bug down.

**Comment by plxity** [comment]
@leMaik  Its working fine now. I uninstalled the package and installed it again. Thanks :)

**Comment by leMaik** [comment]
@plxity That's great to hear :+1:
