### ISSUE TITLE
Cannot customize the icon button appearance

### ISSUE THREAD

**Issue by SanzenDev** [TeamWertarbyte/material-ui-password-field#25]
when I override the visibilityButtonStyle to disabled the background color of the icon button on hover, nothing changed. 
PS: I use it with the Field component of Redux Form

**Comment by leMaik** [comment]
Thanks for reporting this. Indeed, it's not possible to customize the button style at the moment and the readme is wrong.

A new key, e.g. `iconButton` should be added to `styles` so that the class name of the icon button can be set with the `classes` prop. Would you like to submit a PR?

**Comment by leMaik** [comment]
@SanzenDev Fixed in v2.1.0, you can now customize the class names with the `classes` property, as documented [here](https://github.com/TeamWertarbyte/material-ui-password-field#css).
