### ISSUE TITLE
getting below error while trying to install @types/material-ui-password-field

### ISSUE THREAD

**Issue by sajish-sasidharan** [TeamWertarbyte/material-ui-password-field#26]
corpus$ sudo npm install @types/material-ui-password-field
npm ERR! code E404
npm ERR! 404 Not Found: @types/material-ui-password-field@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sajish/.npm/_logs/2019-08-23T09_08_28_755Z-debug.log

**Comment by leMaik** [comment]
There is no `@types/material-ui-password-field` package and this is not the `@types/…` repository. If you want to add typings for this component, you could submit a PR that adds a `PasswordField.d.ts` next to the `PasswordField.js`, like in some our other projects.
