### ISSUE TITLE
Visibility currently isn't working

### ISSUE THREAD

**Issue by BlakeBrown** [TeamWertarbyte/material-ui-password-field#30]
Repro steps:

```
npm i --save material-ui-password-field
import PasswordField from 'material-ui-password-field';

<PasswordField />
```

Clicking the visibility icon currently does nothing :/ I'm trying to debug why.

**Comment by BlakeBrown** [comment]
Was able to resolve with a hack

```
<PasswordField
  visible={this.state.is_password_visible}
  onClick={(e) => {
    if (e.target.nodeName === 'svg') {
      this.setState({
        is_password_visible: !this.state.is_password_visible,
      });
    }
  }} />
```

Might be an issue with our setup, I cloned the repo and it worked fine. We have Next.js and a couple other plugins, so I'll just attribute this to dark sorcery ¯\_(ツ)_/¯

**Comment by leMaik** [comment]
Just remove the visible prop and let the password field handle this internally.

**Comment by leMaik** [comment]
@BlakeBrown I'm very sorry, I was wrong. :scream: An update that fixes this will be out shortly.
